command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=pango

#[window_name]
#command=xprop -id $(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}') | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2 
#interval=repeat

#[window]
##command=while read xtit; do echo $xtit; done < <(xtitle -s)
#command=xtitle -s
#interval=persist
#separator=true

[volume]
label=V:
instance=Master
#instance=PCM
interval=2
signal=10



# Caps Lock indicator
#[keyindicator]
#instance=CAPS
#interval=once
#signal=11

[caps-lock]
command=xset -q | grep Caps | awk '{ print $2 $3 $4 }'
interval=once
signal=10

#[caps-lock]
#command=xset -q | grep Caps | awk '{ print "C:" $4 }'
#interval=once
#signal=10

[wifi]
min_width=20
instance=wlp3s0
interval=10
separator=false

[ssid]
command=echo "$(iw dev wlp3s0 link | grep SSID | cut -d " " -f 2-)"
interval=5
separator=true 

# Battery indicator
[battery]
label=B1:
instance=1
interval=30

[battery]
label=B2:
instance=0
interval=30

# Date Time
[time]
#command=date '+%Y-%m-%d %H:%M'
command=date '+%Y %b %d (%a) %H:%M'
#command=date '+%Y %b %d (%a) %I:%M%p'
#command=date '+%Y-%m-%d  %H:%M'
interval=5
