set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# recize panes
bind-key -r J resize-pane -D 1
bind-key -r K resize-pane -U 1
bind-key -r H resize-pane -L 1
bind-key -r L resize-pane -R 1

# kill window/pane
bind-key & kill-window
bind-key x kill-pane

# pane split
bind-key v split-window -h -c "#{pane_current_path}" # vertical split
bind-key h split-window -v -c "#{pane_current_path}" # horizontal split

# bind T command-prompt -p "Swap current window with?:" "swap-window -t '%1'"
bind-key S command-prompt -p "Swap current pane with?:" "swap-pane -t '%1'"

# reload tmux config
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"


set -g mouse on
