# 1 as base index
set -g base-index 1

set-window-option -g mode-keys vi

# Automaticlly set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Set new Prefix key to C-a
unbind-key C-b
set-option -g prefix C-Space

# No delay for escape key press
set -sg escape-time 0

# no delay with vim
set-option -sg escape-time 0

# reload tmux config
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"


# enable 256 color terminal
set-option -g default-terminal "screen-256color"

# Status bar right side clock
set-option -g status-right "%a %d/%m/%y %H:%M"

#Mouse suport - off to deactivate, on to activate
set -g mouse on
#setw -g mouse-select-pane on
#setw -g mouse-resize-pane on
#setw -g mouse-select-window on

# select panes
bind-key k select-pane -U
bind-key h select-pane -L
bind-key j select-pane -D
bind-key l select-pane -R

# recize panes
bind-key -r J resize-pane -D 1
bind-key -r K resize-pane -U 1
bind-key -r H resize-pane -L 1
bind-key -r L resize-pane -R 1

# kill window/pane
bind-key & kill-window
bind-key x kill-pane

# pane split
bind-key g split-window -h -c "#{pane_current_path}" # vertical split
bind-key v split-window -v -c "#{pane_current_path}" # horizontal split


# bind T command-prompt -p "Swap current window with?:" "swap-window -t '%1'"
bind-key S command-prompt -p "Swap current pane with?:" "swap-pane -t '%1'"


# auto renumber windows sequentially
set-option -g renumber-windows on

set-option -g status "on"

## default statusbar colors
set-option -g status-bg colour237 #bg1
set-option -g status-fg colour223 #fg1
#
## default window title colors
#set-window-option -g window-status-bg colour214 #yellow
#set-window-option -g window-status-fg colour237 #bg1
#
#set-window-option -g window-status-activity-bg colour237 #bg1
#set-window-option -g window-status-activity-fg colour248 #fg3
#
## active window title colors
#set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-fg colour237 #bg1
#
## pane border
set-option -g pane-active-border-fg colour251 #fg2
set-option -g pane-border-fg colour237 #bg1
#
## message infos
#set-option -g message-bg colour239 #bg2
#set-option -g message-fg colour223 #fg1
#
## writting commands inactive
#set-option -g message-command-bg colour239 #fg3
#set-option -g message-command-fg colour223 #bg1
#
## pane number display
#set-option -g display-panes-active-colour colour250 #fg2
#set-option -g display-panes-colour colour237 #bg1
#
## clock
#set-window-option -g clock-mode-colour colour109 #blue
#
## bell
#set-window-option -g window-status-bell-style fg=colour235,bg=colour167 #bg, red
