Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "gb"
        # Option "XkbLayout" "cz,us"
        # Option "XkbModel" "pc104"
        # Option "XkbVariant" ",dvorak"
        Option "XkbVariant" "intlextd"
        # Option "XkbOptions" "grp:alt_shift_toggle"
EndSection
