# change prefix Ctrl-b to Ctrl-a
unbind-key C-b
set-option -g prefix C-a

# select panes
bind-key k select-pane -U
bind-key h select-pane -L
bind-key j select-pane -D
bind-key l select-pane -R

# kill window/pane
bind-key & kill-window
bind-key x kill-pane

# enable 256 color terminal
set-option -g default-terminal "screen-256color"
