# 1 as base index
set -g base-index 1

set-window-option -g mode-keys vi

# Automaticlly set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Set new Prefix key to C-a
unbind-key C-b
set-option -g prefix C-a

# No delay for escape key press
set -sg escape-time 0

# no delay with vim
set-option -sg escape-time 0

# reload tmux config
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"


# enable 256 color terminal
set-option -g default-terminal "screen-256color"

#Mouse suport - off to deactivate, on to activate
set -g mouse on
#setw -g mouse-select-pane on
#setw -g mouse-resize-pane on
#setw -g mouse-select-window on

# select panes
bind-key k select-pane -U
bind-key h select-pane -L
bind-key j select-pane -D
bind-key l select-pane -R

# recize panes
bind-key -r J resize-pane -D 1
bind-key -r K resize-pane -U 1
bind-key -r H resize-pane -L 1
bind-key -r L resize-pane -R 1

# kill window/pane
bind-key & kill-window
bind-key x kill-pane

# pane split
bind-key e split-window -h -c "#{pane_current_path}" # vertical split
bind-key v split-window -v -c "#{pane_current_path}" # horizontal split


# ask user to input window number they wish to swap with
# references: https://stackoverflow.com/questions/33396831/how-to-force-tmux-to-wait-for-output-from-command-prompt
# bind T command-prompt -p "Swap current window with?:" "swap-window -t '%1'"
bind-key S command-prompt -p "Swap current pane with?:" "swap-pane -t '%1'"


# auto renumber windows sequentially
# https://github.com/thoughtbot/dotfiles/blob/master/tmux.conf
set-option -g renumber-windows on

## COLORS ##
# pane divider color; non active pane
set-option -g pane-border-fg green
set-option -g pane-border-bg black

# pane divider color; active pane
# helps when you have more than two panes.
# version 1.8 makes it easy to see 2 panes now
set-option -g pane-active-border-fg white
set-option -g pane-active-border-bg magenta


# command/message line colors
set-option -g message-fg white
set-option -g message-bg black
set-option -g message-attr bright


set-window-option -g monitor-activity on


set-window-option -g window-status-bell-style 'fg=black,bg=colour5,bright'


# statusbar colors
set-option -g status-fg white
set-option -g status-bg black
set-option -g status-attr default

# window title colors; non active
set-window-option -g window-status-fg cyan
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# window title colors; active
set-window-option -g window-status-current-fg white	#font
set-window-option -g window-status-current-bg red	#boarder
set-window-option -g window-status-current-attr bright

#}}}
# LEFT SIDE {{{
set-option -g status-justify centre
set-option -g status-left-length 40
set-option -g status-left "#[fg=green]Session: #S #[fg=yellow]#I #[fg=cyan]#P"

#}}}
# RIGHT SIDE {{{
# use "man date" to set the clock to your liking
set-option -g status-right "#[fg=cyan]%a %d/%m/%y %H:%M"
